#! /usr/local/bin/node

let fs = require('fs')
let Phrase = require('paulos-palindrome')

let text = fs.readFileSync('phrases.txt', 'utf-8')
let palindromes = []
text.split('\n').forEach(function(line){
  let phrase = new Phrase(line)
  if (phrase.palindrome()){
    fs.appendFile('./palindromes.txt', `${line}\n`, (e)=>{if (e) throw e})
  }
})
