#! /usr/local/bin/node
// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.

let url = process.argv[2]

if (!url) {
  console.log(`${url} is not a valid argument`)
  process.exit(1)
}

let request = require('request')
const jsdom = require('jsdom')
const {JSDOM} = jsdom

request(url, function(error, response, body) {
  // Simulate a Document Object Model.
  let {document} = new JSDOM(body).window
  // Grab all the paragraphs and references
  let paragraphs = document.querySelectorAll('p')
  let references = document.querySelectorAll('.reference')
  references.forEach(function(reference){
    reference.remove()
  })
  paragraphs.forEach(function(paragraph){
    console.log(paragraph.textContent)
  })
})